services:

  web:
    build: ./client
    ports:
      - "3000:3000"

  nestjs:
    build: ./server
    ports:
      - "3001:3001"
    environment:
      - DB_URL=mongodb://db:27017/mydatabase
    restart: on-failure
    depends_on:
      - db
      
  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data: