services:

  web:
    build:
      context: ./client
      # Environment variables are being passed in the Dockerfile rather than a .env file
      # due to how Nuxt handles environment variables
    ports:
      - "3000:3000"

  nestjs:
    build: ./server
    ports:
      - "4000:4000"
    env_file: 
      - ./server/.env-docker  # Use the Docker-specific environment file
    restart: on-failure
    depends_on:
      - db
      
  db:
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data: